Menu:
  Home: /
  Archives: /archives/
  About: /about/
  Category: /category_archive
  # Tag: /tag_archive
  Search: false
  
Site:
  Motto: Always do what you're afraid to do. - E. Lockhart

Intro:
  Avastar: img/logo.jpg
  Name: Moxie Deluxe
  Brief: 2013 - Now
  SNS: 
    Weibo:  
    StackOverflow: 
    Github: 
    Pinterest: 
    Quora: 

CopyRight: 
  Author: Moxie Deluxe
  License: 

Tip:
  Alipay: 
  Wechat: 

Comment:
  Id: 8d83609a651e972e308d
  Secret: 37e40c89a47e957f654e86f71c5caaccad0774de
  Repo: Vevlins.github.io
  Owner: Vevlins